[package]
name = "tmns_geotiff"
version = "0.1.0"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
env_logger = "0.11.3"
log = "0.4.21"
tiff = "0.9.1"

[[bin]]
name  = "tmns-geotiff-info"
doc = true
test  = false
bench = false